name: Test the action
on:
  - pull_request
  - push

jobs:
  prettier_test:
    name: Test the plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Testing the action
        uses: ./
