name: Test the action
on:
  - pull_request

jobs:
  prettier_test:
    name: Prettier job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Testing the action
        uses: ./
